on: 
  push:
    branches: 
      - '*'
name: CI/CD
jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100-preview1-014459
    - name: SonarCube Start
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /o:ivanjosipovic /k:IvanJosipovic_BlazorTable /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=$SONARCUBE_TOKEN
      env:
        SONARCUBE_TOKEN: ${{ secrets.SONARCUBE_TOKEN }}
    - name: Dotnet Publish
      working-directory: src/BlazorTable.Sample
      run: dotnet publish --configuration Release
    - name: SonarCube End
      run: |
        dotnet sonarscanner end /d:sonar.login=$SONARCUBE_TOKEN
      env:
        SONARCUBE_TOKEN: ${{ secrets.SONARCUBE_TOKEN }}      
    - name: Deploy to Test
      id: netlify
      uses: ivanjosipovic/actions/cli@master
      with:
        args: deploy --json -d src/BlazorTable.Sample/bin/Release/netstandard2.0/publish/BlazorTable.Sample/dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      uses: ivanjosipovic/actions/cli@master
      with:
        args: deploy --prod --json -d src/BlazorTable.Sample/bin/Release/netstandard2.0/publish/BlazorTable.Sample/dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
